default_stages: [pre-commit]
fail_fast: true

repos:
  - repo: local
    hooks:
      # ========== 后端检查 ==========
      - id: swagger-generate
        name: Generate Swagger docs
        entry: pnpm run gen:swagger
        language: system
        pass_filenames: false
        files: (internal/command/server/[^/]+$|^go\.mod$)

      - id: openapi-generator
        name: Generate TypeScript SDK
        entry: pnpm run gen:openapi
        language: system
        pass_filenames: false
        files: gen/swagger/swagger\.json

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: ["--maxkb=512"]

  - repo: https://github.com/lwmacct/251211-pre-commit
    rev: v1.0.2
    hooks:
      - id: prettier
      - id: mc-mdtoc
      - id: golangci-lint
      - id: config-sync
